// Generated by CoffeeScript 1.7.1
var AfterBrunch, spawn, sysPath;

sysPath = require('path');

spawn = require('child_process').spawn;

module.exports = AfterBrunch = (function() {
  AfterBrunch.prototype.brunchPlugin = true;

  function AfterBrunch(config) {
    var _ref;
    this.config = config;
    this.commands = (_ref = this.config.plugins.afterBrunch) != null ? _ref : [];
  }

  function shspawn(command) {
    spawn('sh', ['-c', command], {stdio: 'inherit'});
  }

  AfterBrunch.prototype.onCompile = function(generatedFiles) {
    var command, _i, _len, _ref;
    _ref = this.commands;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      command = _ref[_i];
      var spwndCmd = shspawn(command);
    }
  };

  return AfterBrunch;

})();
